# Generated by Django 4.1.7 on 2023-12-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_rename_moddified_at_post_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='category', to='blogApp.category'),
        ),
    ]
