# Generated by Django 4.1.7 on 2023-12-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='post', to='blogApp.category'),
        ),
    ]
