# Generated by Django 4.1.7 on 2023-12-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post-images/%Y/%m/%d'),
        ),
    ]
